#!/usr/bin/env python3
"""Build a V2 research case from a case_config.json file.

This script is intentionally conservative. It generates candidate KWIC rows,
candidate evidence rows, and candidate claim rows. It does not produce final
scholarly conclusions; generated outputs must be reviewed by a human researcher
before being copied into the curated case files.
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def resolve_project_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else PROJECT_ROOT / path


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def read_json(path: Path) -> dict[str, object]:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON root must be an object: {path}")
    return data


def write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def read_jsonl(path: Path) -> list[dict[str, object]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    rows: list[dict[str, object]] = []
    with path.open("r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            value = json.loads(line)
            if not isinstance(value, dict):
                raise ValueError(f"JSONL row must be an object at {path}:{line_number}")
            rows.append(value)
    return rows


def load_segments(config: dict[str, object]) -> tuple[Path, list[dict[str, object]], bool]:
    primary = resolve_project_path(str(config["segments"]))
    if primary.exists():
        return primary, read_jsonl(primary), False
    fallback_value = config.get("fallback_segments")
    if fallback_value:
        fallback = resolve_project_path(str(fallback_value))
        if fallback.exists():
            return fallback, read_jsonl(fallback), True
    raise FileNotFoundError(f"Neither primary nor fallback segment file exists: {primary}")


def load_terms(config: dict[str, object]) -> list[str]:
    focus_terms = config.get("focus_terms")
    if isinstance(focus_terms, list) and focus_terms:
        return [str(term) for term in focus_terms if str(term).strip()]
    lexicon = resolve_project_path(str(config["lexicon"]))
    return [row["term"] for row in read_csv(lexicon) if row.get("term")]


def generate_kwic_rows(segments: list[dict[str, object]], terms: list[str], window: int) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for segment in segments:
        text = str(segment.get("text", ""))
        for term in terms:
            start = 0
            while True:
                idx = text.find(term, start)
                if idx == -1:
                    break
                rows.append({
                    "document_id": str(segment.get("document_id", "")),
                    "segment_id": str(segment.get("segment_id", "")),
                    "term": term,
                    "left_context": text[max(0, idx - window):idx],
                    "right_context": text[idx + len(term):idx + len(term) + window],
                    "evidence_quote": text,
                    "review_status": "candidate",
                    "review_note": "Generated by build_case.py from configured segments and focus terms.",
                })
                start = idx + len(term)
    return rows


def generate_evidence_rows(kwic_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for index, row in enumerate(kwic_rows, start=1):
        term = row.get("term", "")
        rows.append({
            "evidence_id": f"EVID-KD-AUTO-{index:05d}",
            "document_id": row.get("document_id", ""),
            "segment_id": row.get("segment_id", ""),
            "term": term,
            "claim_type": "term_context",
            "evidence_quote": row.get("evidence_quote", ""),
            "observation_zh": f"术语「{term}」出现在该段文本中；含义、语境和解释价值需要人工复核。",
            "observation_en": f"The term '{term}' appears in this segment; meaning, context, and interpretive value require human review.",
            "review_status": "candidate",
            "review_note": "Generated from case-level KWIC; not a scholarly conclusion.",
        })
    return rows


def generate_claim_rows(evidence_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for index, row in enumerate(evidence_rows, start=1):
        term = row.get("term", "")
        rows.append({
            "claim_id": f"CLAIM-KD-AUTO-{index:05d}",
            "document_id": row.get("document_id", ""),
            "segment_id": row.get("segment_id", ""),
            "claim_type": row.get("claim_type", "term_context"),
            "claim_text": f"Candidate claim: the segment contains the focus term '{term}' and may be relevant to the Kunyu-Diqiu comparison.",
            "evidence_quote": row.get("evidence_quote", ""),
            "extraction_method": "script",
            "claim_status": "candidate",
            "reviewer": "",
            "review_date": "",
            "uncertainty_note": "Automatically generated from term occurrence. Human review is required before use as a research claim.",
        })
    return rows


def build_case(args: argparse.Namespace) -> None:
    config_path = resolve_project_path(args.config)
    config = read_json(config_path)
    segment_path, segments, used_fallback = load_segments(config)
    terms = load_terms(config)
    window = int(config.get("window", 18))

    kwic_rows = generate_kwic_rows(segments, terms, window=window)
    evidence_rows = generate_evidence_rows(kwic_rows)
    claim_rows = generate_claim_rows(evidence_rows)

    outputs = config.get("outputs")
    if not isinstance(outputs, dict):
        raise ValueError("case_config.json must contain an outputs object")

    kwic_path = resolve_project_path(str(outputs["kwic"]))
    evidence_path = resolve_project_path(str(outputs["evidence"]))
    claims_path = resolve_project_path(str(outputs["claims"]))
    report_path = resolve_project_path(str(outputs["report"]))

    write_csv(
        kwic_path,
        kwic_rows,
        ["document_id", "segment_id", "term", "left_context", "right_context", "evidence_quote", "review_status", "review_note"],
    )
    write_csv(
        evidence_path,
        evidence_rows,
        ["evidence_id", "document_id", "segment_id", "term", "claim_type", "evidence_quote", "observation_zh", "observation_en", "review_status", "review_note"],
    )
    write_csv(
        claims_path,
        claim_rows,
        ["claim_id", "document_id", "segment_id", "claim_type", "claim_text", "evidence_quote", "extraction_method", "claim_status", "reviewer", "review_date", "uncertainty_note"],
    )

    document_counts: dict[str, int] = {}
    term_counts: dict[str, int] = {}
    for row in kwic_rows:
        document_counts[row["document_id"]] = document_counts.get(row["document_id"], 0) + 1
        term_counts[row["term"]] = term_counts.get(row["term"], 0) + 1

    report = {
        "case_id": config.get("case_id"),
        "config": str(config_path),
        "segments": str(segment_path),
        "used_fallback_segments": used_fallback,
        "segment_count": len(segments),
        "focus_term_count": len(terms),
        "kwic_count": len(kwic_rows),
        "evidence_count": len(evidence_rows),
        "claim_candidate_count": len(claim_rows),
        "document_counts": document_counts,
        "term_counts": term_counts,
        "outputs": {
            "kwic": str(kwic_path),
            "evidence": str(evidence_path),
            "claims": str(claims_path),
            "report": str(report_path),
        },
        "status": "candidate_outputs_generated",
        "note": "Generated outputs require human review before being promoted to curated case files.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    write_json(report_path, report)
    print(f"Case built: {config.get('case_id')} | KWIC={len(kwic_rows)} evidence={len(evidence_rows)} claims={len(claim_rows)} report={report_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="build_case", description="Build a V2 case from case_config.json")
    parser.add_argument("--config", default="cases/kunyu_diqiu_comparison/case_config.json")
    return parser


def main(argv: Iterable[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    build_case(args)


if __name__ == "__main__":
    main()
